var P5_postQ = {
"P1_instruct_feedback": "", 
"P1_practicetrial_prep": "yes-prepared", 
"lang_now": "English", 
"prev_experience": "I was shown flashes of images and was told to identify something in the image, and remember a word or something like that", 
"P2_practicetrial_prep": "2yes-prepared", 
"P2_practicetrial_amt": "2more-practice", 
"P1_difficulty": "neither", 
"handedness": "Right", 
"P1_practicetrial_amt": "equal-practice", 
"P2_instruct_feedback": "", 
"P1_instructions": "yes-clear", 
"P2_general": "", 
"P2_difficulty": "2very-difficult", 
"phase": "post-questionnaire", 
"P1_general": "it was difficult to remember words that didn't formulate a sentence", 
"gender": "F", 
"lang_before6": "Romanian, English", 
"age": "20-24", 
"P2_instructions": "2yes-clear"}

var P4_postQ = {
"P1_instruct_feedback": "", 
"P1_practicetrial_prep": "yes-prepared", 
"lang_now": "English, Hindi, French, Spanish and Oriya", 
"prev_experience": "No.", 
"P2_general": "I found it very difficult to move on from the repetition trials to the memory trials. At the beginning of part II, I was a bit confused as to what to do.", 
"P2_practicetrial_amt": "2more-practice", 
"P1_difficulty": "very-easy", 
"handedness": "Right", 
"P1_practicetrial_amt": "more-practice", 
"P2_instruct_feedback": "", 
"P1_instructions": "yes-clear", 
"P2_practicetrial_prep": "2no-unprepared", 
"lang_before6": "Hindi and English", 
"P2_difficulty": "2very-difficult", 
"P1_general": "", 
"gender": "M", 
"phase": "post-questionnaire", 
"age": "19-", 
"P2_instructions": "2yes-clear"}

var P1_postQ = {
	"P1_instruct_feedback": "", 
	"P1_practicetrial_prep": "yes-prepared", 
	"lang_now": "English", 
	"prev_experience": "i've done dual n-back tasks but not with audio and not with this sort of sequential display: usually grid based tasks", 
	"P2_practicetrial_prep": "2yes-prepared", 
	"P2_practicetrial_amt": "2more-practice", 
	"P1_difficulty": "somewhat-easy", 
	"handedness": "Right", 
	"P1_practicetrial_amt": "equal-practice", 
	"P2_instruct_feedback": "", 
	"P1_instructions": "yes-clear", 
	"P2_general": "(I don't see feedback for the memory task (Part III) on this page, so just adding that it wasn't immediately clear what ought to have gone in those boxes, whether they were intended to be listed sequentially as with the tasks)", 
	"P2_difficulty": "2somewhat-difficult", 
	"phase": "post-questionnaire", 
	"P1_general": "n/a", 
	"gender": "x", 
	"lang_before6": "Native English; basic French", 
	"age": "25-29", 
	"P2_instructions": "2yes-clear"}

var P2_postQ = {
	"P1_instruct_feedback": "", 
	"P1_practicetrial_prep": "yes-prepared", 
	"lang_now": "english", 
	"prev_experience": "no", 
	"P2_general": "the instructions were unclear. i was unsure at first if i needed to click the space bar every single time a letter that had previously been said was said again rather than pressing it at instances of imediate repetition", 
	"P2_practicetrial_amt": "2equal-practice", 
	"P1_difficulty": "somewhat-easy", 
	"handedness": "Right", 
	"P1_practicetrial_amt": "equal-practice", 
	"P2_instruct_feedback": "", 
	"P1_instructions": "yes-clear", 
	"P2_practicetrial_prep": "2yes-prepared", 
	"lang_before6": "english", 
	"P2_difficulty": "2somewhat-difficult", 
	"P1_general": "no", 
	"gender": "F", 
	"phase": "post-questionnaire", 
	"age": "20-24", 
	"P2_instructions": "2no-unclear"}

var P3_postQ = {
	"P1_instruct_feedback": "", 
	"P1_practicetrial_prep": "yes-prepared", 
	"lang_now": "English", 
	"prev_experience": "No", 
	"P2_general": "", 
	"P2_practicetrial_amt": "2more-practice", 
	"P1_difficulty": "neither", 
	"handedness": "Right", 
	"P1_practicetrial_amt": "equal-practice", 
	"P2_instruct_feedback": "", 
	"P1_instructions": "yes-clear", 
	"P2_practicetrial_prep": "2no-unprepared", 
	"lang_before6": "English", 
	"P2_difficulty": "2very-difficult", 
	"P1_general": "", 
	"gender": "M", 
	"phase": "post-questionnaire", 
	"age": "20-24", 
	"P2_instructions": "2yes-clear"}